[pytest]
testpaths = lambdas/functions
python_files = test_*_pytest.py
addopts = -v
markers =
    unit: mark a test as a unit test
    integration: mark a test as an integration test
    slow: mark a test as slow
log_cli = true
log_cli_level = INFO
xvs_ignore =
    *.pyc
    *.pyo
    __pycache__ 